app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_admin:
    resource: "@AppBundle/Controller/Admin/"
    type:     annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
