route_category_index:
    path: /
    methods: [GET]
    defaults:
        _controller: app.controller.category:indexAction
        _sylius:
            template: AppBundle:Admin/Category:index.html.twig
            filterable: true
            sortable: true

route_category_create:
    path: /create
    methods: [GET, POST]
    defaults:
        _controller: app.controller.category:createAction
        _sylius:
            template: AppBundle:Admin/Category:create.html.twig
            redirect: route_category_index

route_category_update:
    path: /{id}/update
    methods: [GET, PATCH, PUT]
    requirements:
        id: \d+
    defaults:
        _controller: app.controller.category:updateAction
        _sylius:
            template: AppBundle:Admin/Category:update.html.twig
            redirect: route_category_index

route_category_delete:
    path: /{id}/delete
    methods: [DELETE]
    requirements:
        id: \d+
    defaults:
        _controller: app.controller.category:deleteAction
        _sylius:
            redirect: route_category_index

route_category_show:
    path: /{id}/show
    methods: [GET]
    requirements:
        id: \d+
    defaults:
        _controller: app.controller.category:showAction
        _sylius:
            template: AppBundle:Admin/Category:show.html.twig
