AppBundle\Model\Photo:
    type: entity
    table: hah_photo

    id:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO

    fields:
        title:
            type: string
            nullable: false

        path:
            type: string
            nullable: true

        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create

        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update

    manyToOne:
        category:
            targetEntity: AppBundle\Model\CategoryInterface
            joinColumn:
                nullable: true
                name: category_id
                referencedColumnName: id
                onDelete: "SET NULL"
