services:
    upload_filesystem:
        class: Gaufrette\Filesystem
        factory_service: knp_gaufrette.filesystem_map
        factory_method: get
        arguments:
            - photo_filesystem

    image_uploader:
        class: AppBundle\Uploader\ImageUploader
        arguments:
            - @upload_filesystem

    image_upload_subscriber:
        class: AppBundle\EventListener\ImageUploadSubscriber
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    photo_form_type:
        class: AppBundle\Form\PhotoType
        tags:
            - { name: form.type, alias: photo }
