AppBundle\Model\Photo:
    properties:
        title:
            - NotBlank: ~

        file:
            - NotBlank: ~

            - Image:
                allowLandscape: true
                allowPortrait: true
