AppBundle\Model\SwearWord:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [swear]

    properties:
        swear:
            - NotBlank: ~

        replacement:
            - NotBlank: ~
